'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization
Imports SimpleCrypto

'
'This source code was auto-generated by xsd, Version=4.0.30319.18020.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True), _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)> _
Partial Public Class SettingsXML
    Implements IDisposable

    Private _ContainerData As New SettingsFileContainerData
    Private _DeviceSetings As New SettingsFileDeviceSetings
    Private _PasswordSettings As New SettingsFilePasswordSettings

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ContainerData", GetType(SettingsFileContainerData), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property ContainerData As SettingsFileContainerData
        Get
            Return Me._ContainerData
        End Get
        Set(value As SettingsFileContainerData)
            Me._ContainerData = value
        End Set
    End Property
    <System.Xml.Serialization.XmlElementAttribute("DeviceSetings", GetType(SettingsFileDeviceSetings), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property DeviceSetings As SettingsFileDeviceSetings
        Get
            Return Me._DeviceSetings
        End Get
        Set(value As SettingsFileDeviceSetings)
            Me._DeviceSetings = value
        End Set
    End Property
    <System.Xml.Serialization.XmlElementAttribute("PasswordSettings", GetType(SettingsFilePasswordSettings), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property PasswordSettings As SettingsFilePasswordSettings
        Get
            Return Me._PasswordSettings
        End Get
        Set(value As SettingsFilePasswordSettings)
            Me._PasswordSettings = value
        End Set
    End Property

    Public ReadOnly Property IsCorrupt As Boolean
        Get
            For Each p As System.Reflection.PropertyInfo In Me.DeviceSetings.GetType().GetProperties()
                If p.CanRead Then
                    If p.GetValue(Me.DeviceSetings, Nothing) = "" Then
                        Return True
                    End If
                End If
            Next

            Return False
        End Get
    End Property

#Region "IDisposable Support"
    Private disposedValue As Boolean ' To detect redundant calls

    ' IDisposable
    Protected Overridable Sub Dispose(disposing As Boolean)
        If Not Me.disposedValue Then
            If disposing Then
                ' TODO: dispose managed state (managed objects).
            End If

            ' TODO: free unmanaged resources (unmanaged objects) and override Finalize() below.
            ' TODO: set large fields to null.
            _ContainerData = Nothing
            _DeviceSetings = Nothing
            _PasswordSettings = Nothing
        End If
        Me.disposedValue = True
    End Sub

    ' TODO: override Finalize() only if Dispose(ByVal disposing As Boolean) above has code to free unmanaged resources.
    'Protected Overrides Sub Finalize()
    '    ' Do not change this code.  Put cleanup code in Dispose(ByVal disposing As Boolean) above.
    '    Dispose(False)
    '    MyBase.Finalize()
    'End Sub

    ' This code added by Visual Basic to correctly implement the disposable pattern.
    Public Sub Dispose() Implements IDisposable.Dispose
        ' Do not change this code.  Put cleanup code in Dispose(disposing As Boolean) above.
        Dispose(True)
        GC.SuppressFinalize(Me)
    End Sub
#End Region

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class SettingsFileContainerData

    Private locationField As String = ""

    Private useKeyFileField As Boolean = False

    Private keyFileField As String = ""

    Private removableField As Boolean = False

    Private useBackupField As Boolean = False

    Private readOnlyField As Boolean = False

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property Location() As String
        Get
            Return Me.locationField
        End Get
        Set(value As String)
            Me.locationField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property UseKeyFile() As Boolean
        Get
            Return Me.useKeyFileField
        End Get
        Set(value As Boolean)
            Me.useKeyFileField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property KeyFile() As String
        Get
            Return Me.keyFileField
        End Get
        Set(value As String)
            Me.keyFileField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property Removable() As Boolean
        Get
            Return Me.removableField
        End Get
        Set(value As Boolean)
            Me.removableField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property UseBackup() As Boolean
        Get
            Return Me.useBackupField
        End Get
        Set(value As Boolean)
            Me.useBackupField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property [ReadOnly]() As Boolean
        Get
            Return Me.readOnlyField
        End Get
        Set(value As Boolean)
            Me.readOnlyField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class SettingsFileDeviceSetings

    Private CONTAINER_LABELField As String = ""
    Private KEYFILE_LABELField As String = ""

    Private sECURED_LETTERField As String = ""

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property CONTAINER_LABEL() As String
        Get
            Return Me.CONTAINER_LABELField
        End Get
        Set(value As String)
            Me.CONTAINER_LABELField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property KEYFILE_LABEL() As String
        Get
            Return Me.KEYFILE_LABELField
        End Get
        Set(value As String)
            Me.KEYFILE_LABELField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property SECURED_LETTER() As String
        Get
            Return Me.sECURED_LETTERField
        End Get
        Set(value As String)
            Me.sECURED_LETTERField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class SettingsFilePasswordSettings

    Private masterField As String = ""

    Private trueCryptField As String = ""

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property Master() As String
        Get
            Return Me.masterField
        End Get
        Set(value As String)
            Me.masterField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> _
    Public Property TrueCrypt() As String
        Get
            Return Me.trueCryptField
        End Get
        Set(value As String)
            Me.trueCryptField = value
        End Set
    End Property
End Class


Module CurrentSettingsFile
    Public IsRecovering As Boolean = False

    Public Property CurrentSettings As SettingsXML
        Get
            If Not IO.File.Exists(My.Settings.SettingsFileName) Then CreateNewSettings()

            Dim NewSettings As SettingsXML

            Dim reader As New System.Xml.Serialization.XmlSerializer(GetType(SettingsXML), "")
            Using file As New System.IO.StreamReader(My.Settings.SettingsFileName)
                NewSettings = CType(reader.Deserialize(file), SettingsXML)
            End Using
            reader = Nothing

            If NewSettings.IsCorrupt And Not IsRecovering Then NewOrCorruptSettings(NewSettings)

            Return NewSettings
        End Get
        Set(value As SettingsXML)
            Dim writer As New System.Xml.Serialization.XmlSerializer(GetType(SettingsXML))
            Using file As New System.IO.StreamWriter(My.Settings.SettingsFileName)
                writer.Serialize(file, value)
                writer = Nothing
            End Using
        End Set
    End Property

    Public Sub NewOrCorruptSettings(ByVal CorruptSettings As SettingsXML)
        IsRecovering = True

        Do
            If MessageBox.Show("No settings detected or settings are corrupt. Please create settings for a volume or exit.", "Truecrypt - Automap", MessageBoxButtons.OKCancel, MessageBoxIcon.Warning) = DialogResult.OK Then
                Using SettingDialog As New Settings(CorruptSettings)
                    If SettingDialog.ShowDialog = DialogResult.OK Then
                        CurrentSettings = SettingDialog.NewSettings
                        Exit Do
                    End If
                End Using
            Else
                If MessageBox.Show("Do you really want to exit?", "TrueCrypt - AutoMount", MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button2) = Windows.Forms.DialogResult.Yes Then
                    System.Environment.Exit(0)
                    Exit Sub
                End If
            End If
        Loop

        IsRecovering = False
    End Sub

    Private Sub CreateNewSettings()
        Dim NewSettingsFile As New SettingsXML With { _
                    .PasswordSettings = New SettingsFilePasswordSettings With { _
                        .Master = AES256.HashString("Password")
                    }
                }
        CurrentSettings = NewSettingsFile
    End Sub

End Module
